### ISSUE TITLE
Hardware specs?

### ISSUE THREAD

**Issue by arunimaaaa** [pgupta1795/chat-pdf-llama2#1]
Hi,
What's your hardware specs? I am trying to run a similar model, takes forever for inferencing in CPU.

**Comment by pgupta1795** [comment]
Hi @arunimaaaa ,
I have rtx 3060 gpu 6gb VRAM + 16gb i5 10th gen CPU.
It takes about 2 minutes - 3.5 minutes for a general answer.
If running without GPU it takes 7-10 minutes with only CPU.
How much time it takes for your usecase.
Regards,
Pallav Gupta

**Comment by arunimaaaa** [comment]
I have i7 10th gen. For me i think it took about 12-15 mins for a response.

**Comment by pgupta1795** [comment]
Yea, depending on your data also. It sounds apt. If you have GPU machine, can you try there?
